import { DATES_KEY, DATES_TOPIC } from './dates';
import { TIMES_KEY, TIMES_TOPIC } from './times';
import { NUMBERS_TOPIC } from './numbers';
import { HIRAGANA_TOPIC } from './hiragana';
import { KATAKANA_TOPIC } from './katakana';


export const LIST_OF_TOPICS = [
  DATES_TOPIC,
  TIMES_TOPIC,
  NUMBERS_TOPIC,
  HIRAGANA_TOPIC,
  KATAKANA_TOPIC,
  {
    key: 'random',
    icon: 'far fa-smile-wink',
    title: 'Randomly generated by topic',
    quizzes: [
      { param: DATES_KEY, title: 'Dates' },
      { param: TIMES_KEY, title: 'Times' }
    ]
  }
];
