export const LIST_OF_TOPICS = [
  {
    key: 'dates',
    icon: 'fas fa-calendar-alt',
    title: 'Dates 年月日',
    quizzes: [
      { param: 'months', title: 'Months', },
      { param: 'days_of_the_month', title: 'Days of the month' },
      { param: 'days_of_the_week', title: 'Days of the week' }
    ]
  },
  {
    key: 'times',
    icon: 'fas fa-clock',
    title: 'Times 時間',
    quizzes: [
      { param: 'hours_of_the_day', title: 'Hours of the day' },
      { param: 'minutes_upto_20', title: 'Minutes (1-20)' },
      { param: 'minutes_upto_40', title: 'Minutes (21-40)' },
      { param: 'minutes_upto_60', title: 'Minutes (41-60)' },
    ]
  },
  {
    key: 'numbers',
    icon: 'fas fa-calculator',
    title: 'Numbers 番号',
    quizzes: []
  },
  {
    key: 'random',
    icon: 'far fa-smile-wink',
    title: 'Randomly generated by topic',
    quizzes: [
      { param: 'dates', title: 'Dates' }
    ]
  }
];
