const days_of_the_month = [
  { day: "1st", translations: ["tsuitachi"] },
  { day: "2nd", translations: ["futsuka"] },
  { day: "3rd", translations: ["mikka"] },
  { day: "4th", translations: ["yokka"] },
  { day: "5th", translations: ["itsuka"] },
  { day: "6th", translations: ["muika"] },
  { day: "7th", translations: ["nanoka"] },
  { day: "8th", translations: ["youka"] },
  { day: "9th", translations: ["kokonoka"] },
  { day: "10th", translations: ["touka"] },
  { day: "11th", translations: ["juuichinichi"] },
  { day: "12th", translations: ["juuninichi"] },
  { day: "13th", translations: ["juusannichi"] },
  { day: "14th", translations: ["juuyokka"] },
  { day: "15th", translations: ["juugonichi"] },
  { day: "16th", translations: ["juurokunichi"] },
  { day: "17th", translations: ["juushichinichi"] },
  { day: "18th", translations: ["juuhachinichi"] },
  { day: "19th", translations: ["juukyuunichi", "juukunichi"] },
  { day: "20th", translations: ["hatsuka"] },
  { day: "21st", translations: ["nijuuichinichi"] },
  { day: "22nd", translations: ["nijuuninichi"] },
  { day: "23rd", translations: ["nijuusannichi"] },
  { day: "24th", translations: ["nijuuyokka"] },
  { day: "25th", translations: ["nijuugonichi"] },
  { day: "26th", translations: ["nijuurokunichi"] },
  { day: "27th", translations: ["nijuushichinichi"] },
  { day: "28th", translations: ["nijuuhachinichi"] },
  { day: "29th", translations: ["nijuukyuunichi", "nijuukunichi"] },
  { day: "30th", translations: ["sanjuunichi"] },
  { day: "31st", translations: ["sanjuuichinichi"] }
];

export default days_of_the_month;
