const days_of_the_month = [
  { word: "1st", translations: ["tsuitachi"] },
  { word: "2nd", translations: ["futsuka"] },
  { word: "3rd", translations: ["mikka"] },
  { word: "4th", translations: ["yokka"] },
  { word: "5th", translations: ["itsuka"] },
  { word: "6th", translations: ["muika"] },
  { word: "7th", translations: ["nanoka"] },
  { word: "8th", translations: ["youka"] },
  { word: "9th", translations: ["kokonoka"] },
  { word: "10th", translations: ["touka"] },
  { word: "11th", translations: ["juuichinichi"] },
  { word: "12th", translations: ["juuninichi"] },
  { word: "13th", translations: ["juusannichi"] },
  { word: "14th", translations: ["juuyokka"] },
  { word: "15th", translations: ["juugonichi"] },
  { word: "16th", translations: ["juurokunichi"] },
  { word: "17th", translations: ["juushichinichi"] },
  { word: "18th", translations: ["juuhachinichi"] },
  { word: "19th", translations: ["juukyuunichi", "juukunichi"] },
  { word: "20th", translations: ["hatsuka"] },
  { word: "21st", translations: ["nijuuichinichi"] },
  { word: "22nd", translations: ["nijuuninichi"] },
  { word: "23rd", translations: ["nijuusannichi"] },
  { word: "24th", translations: ["nijuuyokka"] },
  { word: "25th", translations: ["nijuugonichi"] },
  { word: "26th", translations: ["nijuurokunichi"] },
  { word: "27th", translations: ["nijuushichinichi"] },
  { word: "28th", translations: ["nijuuhachinichi"] },
  { word: "29th", translations: ["nijuukyuunichi", "nijuukunichi"] },
  { word: "30th", translations: ["sanjuunichi"] },
  { word: "31st", translations: ["sanjuuichinichi"] }
];

export default days_of_the_month;
